plugins {
    id 'multiloader-common'
}

configurations {
    commonJava{
        canBeResolved = true
    }
    commonResources{
        canBeResolved = true
    }
}

dependencies {
    compileOnly(project(':common')) {
        capabilities {
            requireCapability "$group:$mod_id"
        }
    }
    commonJava project(path: ':common', configuration: 'commonJava')
    commonResources project(path: ':common', configuration: 'commonResources')
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

tasks.named('javadoc', Javadoc).configure {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.commonJava)
    from(configurations.commonJava)
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

def publishDir = rootProject.layout.projectDirectory.dir("Publish")
tasks.register('copyJarToPublish', Copy) {
    into(publishDir)
}

afterEvaluate {
    tasks.named('copyJarToPublish', Copy) {
        def remapTask = tasks.findByName('remapJar')
        if (remapTask != null) {
            dependsOn(remapTask)
            from(remapTask.archiveFile)
        } else {
            def jarTask = tasks.named('jar')
            dependsOn(jarTask)
            from(jarTask.flatMap { it.archiveFile })
        }
    }
}

tasks.named('build') {
    finalizedBy(tasks.named('copyJarToPublish'))
}
